### PR TITLE
WIP integrate linkedin/cruise-control, fixes #100

### LINKED ISSUE #100: Maybe add linkedin/cruise-control?
Just an idea... cruise control is great

### PR DESCRIPTION
**Pull request by double16**
linkedin/cruise-control automates much of the operations of Kafka.

I present this PR for discussion.

### CODE REVIEW

**Comment by solsson** [comment]
How about we merge to master instead of 4.x, or are we lacking compatibility with Kafka 2.x?

**Comment by double16** [comment]
master sounds good to me. Kafka 2.x is supported with this version of cruise-control.

**Comment by solsson** [comment]
I get a crashloop after merge to master:

```
288    [           main] WARN  lients.consumer.ConsumerConfig  - The configuration 'sample.store.class' was supplied but isn't a known config.
288    [           main] WARN  lients.consumer.ConsumerConfig  - The configuration 'default.goals' was supplied but isn't a known config.
289    [           main] INFO  fka.common.utils.AppInfoParser  - Kafka version : 2.0.0
290    [           main] INFO  fka.common.utils.AppInfoParser  - Kafka commitId : 3402a8361b734732
415    [           main] INFO  .apache.kafka.clients.Metadata  - Cluster ID: n3QC-MxtQZeaRQG7avwTxQ
Exception in thread "main" java.lang.IllegalStateException: Cruise Control cannot find sampling topic matches __CruiseControlMetrics in the target cluster.
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.configure(CruiseControlMetricsReporterSampler.java:207)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1076)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:129)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:69)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:157)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:113)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:106)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:67)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
```

Could it be because of #221?

**Comment by double16** [comment]
Yes, it's because of #221. If cruise-control supports creating the topic it isn't obvious. May need to do that in the init container.

**Comment by solsson** [comment]
I'd like to start with the latest version. Support for 2.x seems to be a WIP so we'll need to follow new releases I think. The warnings don't block merge, we can look at them once up and running. I'll try 2.0.17.

For the usage there should be a README in the cruise-control folder. We can start small. What I thought was that it would be great to prove if some essential automation use case is working. Under replicated partitions etc.

**Comment by solsson** [comment]
Are you ok with the last three commits in https://github.com/Yolean/kubernetes-kafka/compare/cruise-control-reconfig?expand=1 ?

I found a really bad effect of keeping patch files this way, same as with ./metrics/ probably. I wanted to uninstall cruise-conrol so I did `kubectl delete -f cruise-control/` and got this `statefulset.apps "kafka" deleted` 😬 . I'm still in dev of course.

**Comment by double16** [comment]
Yes, those commits are better. Especially preventing delete! Would you like me to work on the README?

**Comment by solsson** [comment]
Actually it'll be a bit of a pain to keep the two image in sync, the one with the metrics jar and the actual cruise control image. Maybe https://github.com/Yolean/kubernetes-kafka/pull/218/files#diff-36facb0f724a84076b8a2525be1c081aR11 should be the actual cruise control image. Should I add the cruise control build to https://github.com/solsson/dockerfiles?

**Comment by double16** [comment]
I think moving the cruise-control image to https://github.com/solsson/dockerfiles is a good idea for maintenance reasons. (FYI, cruise-control 2.0.18 has been released). There isn't a good reason to keep a separate cruise-control and cruise-control-reporter image, I say pull the report jar from the cruise-control image.

As to the `CLASSPATH` var... yeah, that's how the Kafka script is written. Providing the extensions dir up a level would be great for other integrations.

I've started a README, let me know which of these things you'd like me to work on so we're not duplicating effort.

**Comment by solsson** [comment]
I interpret https://github.com/apache/kafka/blob/2.1/bin/kafka-run-class.sh#L129 as wildcard being supported for CLASSPATH, so I'll go for the generalization of the extensions mechanism.

**Comment by solsson** [comment]
Currently blocked by https://github.com/solsson/dockerfiles/pull/20#issuecomment-449512740. Better luck tomorrow maybe.

**Comment by solsson** [comment]
After 432f1e8 and 7cf81da all that remains is testing. The new image build is completely untested.

**Comment by double16** [comment]
I'm working on testing replacement of broker nodes.

**Comment by double16** [comment]
I've tested starting with 3 nodes, then scaling up and down. Cruise control re-assigns partitions to balance as expected. When scaling down to 2 it doesn't do anything, but that may be a config item where the min number of nodes is 3.

**Comment by solsson** [comment]
I haven't done any real testing, but I'm fairly confident that the addition of the extensions mechanism to core Kafka is low risk. The rest is opt-in. Before merge I'd like us to consider adding a bit more to the readme:
 * Guidance on patching, like in https://github.com/Yolean/kubernetes-kafka/tree/master/prometheus#export-metrics-to-prometheus, maybe?
 * Disclaimers, maybe? On the one hand this entire repository serves as an example, on the other hand cruise control introduces a level of automation that we haven't had before.
 * Some guidance on the configuration. There's quite a few files to learn about. Is it based on some reference config? Is it opinionated in some way?

**Comment by double16** [comment]
I added to the README, what do you think?

**Pull request merged**
