### PR TITLE
Send Kafka a TERM signal at pod stop and wait for shutdown

### LINKED ISSUE #206: Issues when forced to rebuild corrupted index
Found an issue with kafka nodes are coming up again after having failed. If they wake up to a corrupted index, it will attempt to fix itself. This seems to have two major implications:
- Memory consumptions goes out the roof, resulting in pod getting killed due to OOM (due to limits, of course)
- Readiness probe fails, and will kill the pod if it hasn't already OOM'ed

Any thoughts on how to remedy this?

### PR DESCRIPTION
**Pull request by solsson**
Fixes #206.

Based on https://github.com/apache/kafka/blob/trunk/bin/kafka-server-stop.sh and https://github.com/apache/kafka/blob/trunk/bin/zookeeper-server-stop.sh but these scripts don't wait for shutdown to complete.

Got the wait loop from https://stackoverflow.com/questions/17894720/kill-a-process-and-wait-for-the-process-to-exit

Currently I've only tested the PR locally with little load. @stigok Can you confirm that you no longer get corrupted indices?

### CODE REVIEW

**Comment by solsson** [comment]
The last log entry I see is `INFO [KafkaServer id=0] shut down completed (kafka.server.KafkaServer)`

**Comment by solsson** [comment]
Maybe Zookeeper doesn't need controlled shutdown. I see no effect in logs of invoking the script.

**Comment by stigok** [comment]
I unable to reproduce bad indices. I don't know how I ended up with them in the first place. We've been having *a lot* of pod restarts and failed probes running in AKS, so it could've been caused by so many different factors.

**Comment by stigok** [comment]
But this is PR os certainly a step in the right direction :+1:

**Comment by stigok** [comment]
I had bad indexes again after my disks went full. Maybe that is a "good way" to simulate broken indexes.
- Configure `log.retention.bytes` to a value greater than available disk-space
- Produce enough messages to fill the disk
- Watch Kafka die
- Expand disk and expect to see bad indexes

**Pull request merged**
