### PR TITLE
Disable automatic topic creation

### PR DESCRIPTION
**Pull request by solsson**
See the commit comment for why.

### CODE REVIEW

**Comment by atamon** [comment]
LGTM! 👍 

Also: 🍰 🍾 

Scope creep: Is our topic automation generic/useful enough to include in this open-source project? Maybe a sample job that describes how we do it?

**Comment by solsson** [comment]
#121 has quite good examples of topic creation

**Comment by solsson** [comment]
Just found #3 :)

**Comment by solsson** [comment]
It's worth noting here that release notes for 2.1.0 mention "Admin script and admin client API improvements to simplify admin operation (KIP-231, KIP-308, KIP-322, KIP-324, KIP-338, KIP-340)"

**Comment by solsson** [comment]
There's a standalone topic creation example, with resource limits, now in events-kube.

**Pull request merged**
