### PR TITLE
Try KSQL

### PR DESCRIPTION
**Pull request by solsson**
In [client-server mode](https://github.com/confluentinc/ksql/blob/0.1.x/docs/concepts.md#client-server-mode) using image from https://github.com/solsson/dockerfiles/pull/15

### CODE REVIEW

**Comment by solsson** [comment]
Looks like https://github.com/solsson/dockerfiles/pull/15/commits/1a53770608741619a49786a6e702c6d57a75156d solves the ClassNotFoundException. New image is building at https://hub.docker.com/r/solsson/kafka-ksql

**Comment by solsson** [comment]
Now it's possible to get a `ksql>` prompt (as in the [quickstart](https://github.com/confluentinc/ksql/tree/0.1.x/docs/quickstart#quick-start)), through `kubectl apply -R -f ksql/`.

**Comment by clintfred** [comment]
@solsson Anything obvious that would make merging `master` into this branch a bad idea?

**Comment by solsson** [comment]
@clintfred I guess KSQL has matured quite a bit since my initial experiment. We found no internal use case for it at the time, so I haven't used KSQL since. If anyone is interested I can do the docker build to upgrade KSQL, but others would have to validate the setup.

**Comment by pavel-agarkov** [comment]
@solsson - I've been using `ksql-developer-preview` branch to play with KSQL on dev.
I would like to continue using KSQL in prod as well.

**Comment by clintfred** [comment]
@solsson Would you also bring all the changes on `master` into the `ksql-developer-preview` in addition to the new docker build of KSQL? I'm not sure what might be involved there...

I'm not in a position where I can yet validate a new setup, but perhaps @pavel-agarkov or someone else could pick that up?

**Comment by solsson** [comment]
I've given up on building this, at https://github.com/solsson/dockerfiles/commit/1b2099b2e0e927acc8cb9eb8cbd46189ab103d4a, so let's go for #164 instead.

**Pull request closed without merging**
