### PR TITLE
Fix Zookeeper persistence

### PR DESCRIPTION
**Pull request by solsson**
Topic information, though not the contents kept in Kafka, would be lost if all zookeeper pods had been down at the same time. Only the snapshots were actually saved to the persistent volume.

According to https://zookeeper.apache.org/doc/r3.4.13/zookeeperAdmin.html#sc_dataFileManagement "ZooKeeper can recover using this snapshot".

The regression probably dates back to https://github.com/Yolean/kubernetes-kafka/commit/ccb9e5df12e5dbe70f243432d1613bd101b35630 which was released with v2.0.0.

### CODE REVIEW

**Comment by solsson** [comment]
The upgrade path would have been smoother if log dir was put inside snapshot dir, but they recommend against that in https://zookeeper.apache.org/doc/r3.4.13/zookeeperAdmin.html#sc_dataFileManagement. It could be that some setups add a separate volume for `/var/lib/zookeeper/log` instead.

Maybe the safest way is to back up `/var/lib/zookeeper`, add a `sleep infinity` at the top of init.sh and restart. Back up from inside the cluster is probably preferred, but `kubectl -n kafka cp zoo-1:/var/lib/zookeeper zoo-1` is also possible. Also note that it's best to experiment with the `zoo` statefulset first as it has a minority of nodes.

**Comment by pavel-agarkov** [comment]
Took me a while to make it work on my single node setup.
I don't know why it worked previously but now it didn't until I changed
```yaml
# maxClientCnxns changed from 1 to 2
zookeeper.properties: |-
  ...
  maxClientCnxns=2
  ...
```
and some other fixes probably also related to the single node setup.

But I will know for sure how it works only after a few days of natural nodes killing 😅

**Comment by solsson** [comment]
@pavel-agarkov 

> maxClientCnxns=2

The line is still there. See #230. I should make the change you suggested and release again... but... Did you see any error message that was specific about hitting this limit? That's what I wanted to experience before I started raising the limit.

**Comment by pavel-agarkov** [comment]
Yes, the whole log was filled with:
> [2018-12-03 08:39:29,911] WARN Too many connections from /10.40.21.8 - max is 1 (org.apache.zookeeper.server.NIOServerCnxnFactory)

**Comment by pavel-agarkov** [comment]
I haven't investigated it at that time and I failed to find it in logs now.

**Comment by pavel-agarkov** [comment]
It still works well after a week of pods killing. Topics are not being lost any more.
Thank you.

**Pull request merged**
